export const CONSTANTS = {
    "ADD_ITEM": "ADD_ITEM",
    "ADD_LIST": "ADD_LIST",
    "DELETE_ITEM": "DELETE_ITEM",
    "DELETE_LIST": "DELETE_LIST",
    "RE_ORDER": "RE_ORDER",
    "UPDATE_STATE": "UPDATE_STATE"
};